### ISSUE TITLE
scalelite

### ISSUE THREAD

**Issue by secretreal26** [greenstatic/bigbluebutton-monitoring#3]
Hi,

Did you try on scalelite ? Is it not compatible ?

Regards,

**Comment by greenstatic** [comment]
We haven't tried scalelite yet, but as far as I understand scalelite is just an application load balencer for BBB. The API for each BBB should still be available, which is what this project requires. But each server would require a deployment of this mini app, there is no support for showing multiple BBB servers on one page.
